### ISSUE TITLE
yarn deploy:scrollTestnet

### ISSUE THREAD

**Issue by samanhoseinpour** [scroll-tech/scroll-contract-deploy-demo#6]
I'm using hardhat and I got a type error when using this command - **yarn deploy:scrollTestnet**

<img width="1188" alt="Screenshot 2023-04-04 at 4 31 50 PM" src="https://user-images.githubusercontent.com/105006550/229799945-1e018595-0191-49d4-87c5-cdae64efb431.png">

**Comment by Thegaram** [comment]
Have you followed step 3 from the instructions?

3. Create an `.env` file following the example `.env.example` in the root directory. Change `PRIVATE_KEY` to your own account private key in the `.env` file.

**Comment by samanhoseinpour** [comment]
already create .env file, should I put my private key into a string?

**Comment by Thegaram** [comment]
Make sure `.env` contains this line:

```
SCROLL_TESTNET_URL=https://alpha-rpc.scroll.io/l2
```

**Comment by samanhoseinpour** [comment]
It doesn't work sit. My .env file has this URL. 
Please show me the correct way...

**Comment by pajicf** [comment]
Hey @samanhoseinpour, can you please send us what your `.env` file looks like (of course, removing the value for the private key) and confirm it's located in the root of the project?

**Comment by samanhoseinpour** [comment]
Here you are. 
<img width="1512" alt="Screenshot 2023-04-06 at 3 14 22 PM" src="https://user-images.githubusercontent.com/105006550/230367069-ab008de8-a1c6-4d52-aae3-cf041bec3931.png">

**Comment by samanhoseinpour** [comment]
Should i send my public key or private key ? 
I'm so confused. When i put my public key in, it worked (line get orange color) and while when I put my private key it wasn't work (line get white color).

**Comment by pajicf** [comment]
You should create a new file called `.env` and paste values from `.env.example` file.
You should put your private key there. You can put it around " " just to be sure, but make sure there aren't any extra spaces if you do 😃

**Comment by samanhoseinpour** [comment]
Thanks sir. It worked ✅.
